# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    steps:
        - run:
            name: Convert noteebook to html
            command: 
                jupyter nbconvert --to html lr.ipynb
         
        - store_artifacts:
            path: /lr.html
            destination: artifact-file